### ISSUE TITLE
Light Sensor and Distance Sensor work when not connected to power

### ISSUE THREAD

**Issue by jmcpeak2** [myjeeed/MakerWear#15]
Second map function needs to be fixed. For example, in Light Sensor code:

```
if (output_value > input_val/4)
    output_val = input_val/4;
else if(output_val < 0)
    output_val = 0;
```

should be added after second map function

**Comment by myjeeed** [comment]
The LightSensor is fixed.
@alexjiao125 is now working on the DistanceSensor.
