### ISSUE TITLE
TemperatureReader: needs calibration

### ISSUE THREAD

**Issue by myjeeed** [myjeeed/MakerWear#21]
Currently the output is not ranging a wide range of temperatures, however the MLX90614 datasheet mentions that it actually does sense temperatures between -70 to 382.2 °C.
So there could be two problems:
- the library that I am currently using (its the Adafruit version)
- I am not providing that temperature (which I tested a few times with the soldering iron, but it didn't go that high - around 60 °C at most) or because of the view angle, it was not able to detect that temperature.

**Comment by jonfroehlich** [comment]
Should also experiment with distance of object from sensor.

**Comment by myjeeed** [comment]
The current temperature mapping is 0°C - 65°C (32°F - 150°F) to 0 - 255 output PWM.
