### ISSUE TITLE
SoundSensor

### ISSUE THREAD

**Issue by myjeeed** [myjeeed/MakerWear#23]
Maybe the problem is from the microphone.

**Comment by myjeeed** [comment]
ok, got it to work. needs calibration.

**Comment by myjeeed** [comment]
After testing different things on this module, we finally understood that the current architecture is not in favor of the SoundSensor. The RC filter on the output of this module will not allow the high frequencies that could be seen in sound signals.

But in short, I was not able to get it to work on this settings: 
SoundSensor module(https://www.adafruit.com/products/1713) + ATmega328 + RC filter connecting its output to an ATtiny85 + LED. I wasn't able to get clean values from the whole system.

**Comment by jonfroehlich** [comment]
Hmm, that makes sense. Can we eliminate RC filter on this module to allow higher frequency (acknowledging that the output will be noisier in general). 

I think reacting to sound is super important.

**Comment by myjeeed** [comment]
Closing this issue. Opening new issues regarding the SoundSensor.
