### ISSUE TITLE
Sender/Receiver

### ISSUE THREAD

**Issue by myjeeed** [myjeeed/MakerWear#29]
Two new modules that would enable wireless communication between modules using infrared transmitters and receivers.

**Comment by myjeeed** [comment]
@alexjiao125 has tested the Sender module with a 100Ω resistor. We might want to reduce this to get higher ranges!

![screen shot 2016-06-13 at 4 12 55 pm](https://cloud.githubusercontent.com/assets/9346800/16021629/b4a9e72e-3181-11e6-8292-eeb0027dda10.png)

**Comment by jonfroehlich** [comment]
What are the current ranges like?

**Comment by myjeeed** [comment]
We didn't do much of an accurate experiment, however it was working in 5-6 meters! But this is definitely a ToDo item for us to estimate the distance.

**Comment by myjeeed** [comment]
Regarding the confusing output pin for the Sender module: the output pin to send data through IR for the Arduino Uno/Arduino Mini/Arduino Lilypad is Pin 3. This is indicated in the IRemote2Int.h with `#define IR_USE_TIMER2 // tx = pin 3` which is on the last `#if defined`, `#elif defined`, and `#else` statements.

**Comment by myjeeed** [comment]
Receiver needs to turn off its output whenever input is low.

**Comment by myjeeed** [comment]
Brainstorming different icons here:
![image](https://cloud.githubusercontent.com/assets/9346800/16455602/ef5f024c-3de2-11e6-82b6-67bd58baf20f.png)
![image](https://cloud.githubusercontent.com/assets/9346800/16455621/0014d8be-3de3-11e6-8f6e-ab1f84263013.png)
![image](https://cloud.githubusercontent.com/assets/9346800/16455631/06325730-3de3-11e6-9454-918756309f0b.png)
![image](https://cloud.githubusercontent.com/assets/9346800/16455636/0cc29510-3de3-11e6-9fba-3fffda0d5f56.png)
![image](https://cloud.githubusercontent.com/assets/9346800/16455643/10ef3f80-3de3-11e6-8a35-c082b8dc8594.png)
![image](https://cloud.githubusercontent.com/assets/9346800/16455693/4ad895d4-3de3-11e6-8308-e48ebd79b095.png)

**Comment by jonfroehlich** [comment]
I like arrow design. Then receiver can have arrows coming inwards.

I think you only need maybe ~3 arrows rather than 5. Also, make the points
sharper so that they are more clear. You are using rounded edges now.

On Wed, Jun 29, 2016 at 10:20 AM, Majeed notifications@github.com wrote:

> Brainstorming different icons here:
> [image: image]
> https://cloud.githubusercontent.com/assets/9346800/16455602/ef5f024c-3de2-11e6-82b6-67bd58baf20f.png
> [image: image]
> https://cloud.githubusercontent.com/assets/9346800/16455621/0014d8be-3de3-11e6-8f6e-ab1f84263013.png
> [image: image]
> https://cloud.githubusercontent.com/assets/9346800/16455631/06325730-3de3-11e6-9454-918756309f0b.png
> [image: image]
> https://cloud.githubusercontent.com/assets/9346800/16455636/0cc29510-3de3-11e6-9fba-3fffda0d5f56.png
> [image: image]
> https://cloud.githubusercontent.com/assets/9346800/16455643/10ef3f80-3de3-11e6-8a35-c082b8dc8594.png
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/myjeeed/MakerWear/issues/29#issuecomment-229370639,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABi-9ebnJQXaniCjLmA_iQZDp9VJLz_qks5qQn8hgaJpZM4IzmNl
> .

## 

Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich https://twitter.com/jonfroehlich - Twitter

**Comment by jmcpeak2** [comment]
These modules transmit analog values now and are working much better as a result.

We are able to transmit across somewhat large distances (around 30 ft), but only if the sender was aligned perfectly with the receiver. Perhaps we can find an IR transmitter that isn't as directional but instead transmits in more of a sphere or cone?

**Comment by myjeeed** [comment]
Me, Alex and Jason personally liked the first three icons! :) So I made the icon based on something similar and I think it looks nice! what do you think Jon?

![image](https://cloud.githubusercontent.com/assets/9346800/16742723/eb172f0a-4776-11e6-8dca-277a24185c66.png)

![image](https://cloud.githubusercontent.com/assets/9346800/16742726/f100c6f6-4776-11e6-95f0-77f5cc3f8119.png)

**Comment by jonfroehlich** [comment]
I think this is too way to subtle for young children. It's very hard to understand direction, which seems really important. I think maybe arrows are necessary.

**Comment by myjeeed** [comment]
So something like this?

![image](https://cloud.githubusercontent.com/assets/9346800/16743594/2a2d9004-477b-11e6-97a3-752993fd413a.png)

![image](https://cloud.githubusercontent.com/assets/9346800/16743604/31967306-477b-11e6-8fca-8f37eb0d8422.png)

**Comment by jonfroehlich** [comment]
Hmm. I don't know. This still feels really abstract to me. 

How about try the wifi signals again but w arrows underneath to strengthen understanding of directionality

**Comment by myjeeed** [comment]
What about this?

![image](https://cloud.githubusercontent.com/assets/9346800/16813417/5bb370aa-48ff-11e6-87d2-42c6b437d5a5.png)

or this:
![image](https://cloud.githubusercontent.com/assets/9346800/16813503/bb06e104-48ff-11e6-863c-0227b9a8fa2a.png)

**Comment by myjeeed** [comment]
and this for the receiver module:
![image](https://cloud.githubusercontent.com/assets/9346800/16813561/11760aba-4900-11e6-88c3-5afb1371e8dc.png)

**Comment by jonfroehlich** [comment]
Hmm, I think having the WiFi like signal at the top is confusing. It seems
like the module is doing two things now rather than one.

How about putting arrows directly under the wifi signals as I previously
suggested. Here's a crappy mock that would need to be cleaned up.

[image: Inline image 1]

I would also ask others. I could certainly be wrong about this.

On Wed, Jul 13, 2016 at 1:45 PM, Majeed notifications@github.com wrote:

> and this for the receiver module:
> [image: image]
> https://cloud.githubusercontent.com/assets/9346800/16813561/11760aba-4900-11e6-88c3-5afb1371e8dc.png
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/myjeeed/MakerWear/issues/29#issuecomment-232432474,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABi-9bDUYouwSKnqvpJhInaFtVkkedbwks5qVSQ9gaJpZM4IzmNl
> .

## 

Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich https://twitter.com/jonfroehlich - Twitter

**Comment by myjeeed** [comment]
@jonfroehlich Your image has not loaded. can you please upload it again?

**Comment by jonfroehlich** [comment]
![image](https://cloud.githubusercontent.com/assets/1621749/16815116/a4f24816-4906-11e6-9586-8e19769f59bb.png)

**Comment by myjeeed** [comment]
I thought that might be too cluttered, so I came up with this:
![image](https://cloud.githubusercontent.com/assets/9346800/16822420/556b359a-492a-11e6-9768-8cf4d934f8f2.png)
![image](https://cloud.githubusercontent.com/assets/9346800/16822455/9699fd8a-492a-11e6-9197-1a94793061cc.png)
![image](https://cloud.githubusercontent.com/assets/9346800/16822546/34155474-492b-11e6-980c-1f53338a4f4c.png)

**Comment by jonfroehlich** [comment]
I like top best. Will that design work on laser cutter?

**Comment by myjeeed** [comment]
I think so! will test it now :)
