### ISSUE TITLE
Rotator

### ISSUE THREAD

**Issue by myjeeed** [myjeeed/MakerWear#30]
New servo motor module that would change the angle of the propeller based on input voltage values. This module is not able to work properly using the ATtiny85 (because of not having a 16 bit timer), that is why we are moving to an ATmega328 for this important module.

**Comment by jonfroehlich** [comment]
Can you put in a sketch (paper sketch is fine) about how you expect this to look and operate from an end-user's perspective?

**Comment by myjeeed** [comment]
Something like this but without the wires and the servo motor glued to the top PCB:
![img_9700](https://cloud.githubusercontent.com/assets/9346800/16420344/f3ce5ba8-3d1e-11e6-87eb-d54405b19503.JPG)

**Comment by jonfroehlich** [comment]
Looks good. 

I'm not sure 'rotator' is a good enough name for this module. Feels too similar to the spinner. Can you guys brainstorm alternatives. Need to emphasize the additional control that you get w rotator.

**Comment by myjeeed** [comment]
I've designed and 3D printed a LEGO shaft for this module, there is a video of it here: https://www.dropbox.com/s/46hk4tm24y1mfg8/Video%20Jul%2011%2C%2011%2002%2050%20AM.mov?dl=0

I think that the shaft is currently too big, and a 2x2 LEGO would work better. What do you think?

**Comment by jonfroehlich** [comment]
I think 2x2 or 2x4 (as you have) are fine. Could try both.

I'd also just like to have some dummy modules that have LEGO attachment
pegs. That is, a hex module with LEGO pegs but is not electronic. Does this
make sense?

On Mon, Jul 11, 2016 at 11:18 AM, Majeed notifications@github.com wrote:

> I've designed and 3D printed a LEGO shaft for this module, there is a
> video of it here:
> https://www.dropbox.com/s/46hk4tm24y1mfg8/Video%20Jul%2011%2C%2011%2002%2050%20AM.mov?dl=0
> 
> I think that the shaft is currently too big, and a 2x2 LEGO would work
> better. What do you think?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/myjeeed/MakerWear/issues/30#issuecomment-231766734,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABi-9WvyHad3PK5r-OjK0d7l3UtoKu94ks5qUl7jgaJpZM4IzmS-
> .

## 

Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich https://twitter.com/jonfroehlich - Twitter

**Comment by myjeeed** [comment]
Yep, we're working on the Dummy module as well. We're currently aiming for the following types of Dummy modules:
- 3x Velcro
- 3x LEGO
- 3x Magnetic
- 3x Drawing

I can't think of any other Dummy modules that might be related to clothes. So please let me know if you have anything in mind.

**Comment by jonfroehlich** [comment]
Velcro provides an opportunity to easily attach fabric, etc. so I think we
have that partially covered.

On Mon, Jul 11, 2016 at 11:37 AM, Majeed notifications@github.com wrote:

> Yep, we're working on the Dummy module as well. We're currently aiming for
> the following types of Dummy modules:
> - 3x Velcro
> - 3x LEGO
> - 3x Magnetic
> - 3x Drawing
> 
> I can't think of any other Dummy modules that might be related to clothes.
> So please let me know if you have anything in mind.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/myjeeed/MakerWear/issues/30#issuecomment-231772482,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABi-9WJvEeKmBF8jbPQV-pMCvtNa4sGZks5qUmMcgaJpZM4IzmS-
> .

## 

Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich https://twitter.com/jonfroehlich - Twitter

**Comment by myjeeed** [comment]
We don't have that much space for the cover of this module, is this alright?
![image](https://cloud.githubusercontent.com/assets/9346800/16813337/0422190e-48ff-11e6-9189-6142781fb8ba.png)

**Comment by jonfroehlich** [comment]
Yes, I like this!

On Wed, Jul 13, 2016 at 1:38 PM, Majeed notifications@github.com wrote:

> We don't have that much space for the cover of this module, is this
> alright?
> [image: image]
> https://cloud.githubusercontent.com/assets/9346800/16813337/0422190e-48ff-11e6-9189-6142781fb8ba.png
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/myjeeed/MakerWear/issues/30#issuecomment-232430454,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABi-9fhaT4WqKueNeSSJMvPTkKrM0dITks5qVSKOgaJpZM4IzmS-
> .

## 

Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich https://twitter.com/jonfroehlich - Twitter
