### ISSUE TITLE
TemperatureReader

### ISSUE THREAD

**Issue by myjeeed** [myjeeed/MakerWear#31]
This module also didn't work on the ATtiny85 for some unknown reasons!

**Comment by jonfroehlich** [comment]
Is this the instantaneous temperature reader or the ambient temperature reader?

**Comment by myjeeed** [comment]
This is the instantaneous temperature reader. And it is currently mapping 0°C - 65°C (32°F - 150°F) to 0 - 255 PWM values.

These values are arbitrary, and we think that kids won't be experimenting with colder or hotter temperatures, while also making sure that different temperatures will make a noticeable difference in the output voltage.

**Comment by jonfroehlich** [comment]
What happens if you point it at ice... Do you get 0 Celsius reading?

**Comment by myjeeed** [comment]
Yes, but we do not have a very good way of visualizing the number. Because the output values of this module, as well as the DistanceSensor will map into some sort of analog values but they almost do not have any meaning, though you can see the differences.

But yes, pointing this to ice (or a bottle of cold water in the SnackerSpace) will result in 0, which will cause the Number module to also show 0 as well. And pointing it to hot water will result in 7-8 on the Number module.

**Comment by myjeeed** [comment]
Liang made this icon, I think it's good. But it doesn't indicate that it's a point sensor (well, because it wasn't a point sensor back then!)
![image](https://cloud.githubusercontent.com/assets/9346800/16455875/e4f33e3a-3de3-11e6-992b-88765892ba9a.png)

**Comment by jonfroehlich** [comment]
I agree. Would be good to indicate that TemperatureReader can be pointed at
objects and read their temperature. How about something that shows a little
hexagonal module with a dashed line with an arrow to an object (like Ice or
Fire) and then another dashed line that comes back from object to module
with temperature. Can you brainstorm?

Maybe also change name to: Object Temperature Scanner or something?

On Wed, Jun 29, 2016 at 10:38 AM, Majeed notifications@github.com wrote:

> Liang made this icon, I think it's good. But it doesn't indicate that it's
> a point sensor:
> [image: image]
> https://cloud.githubusercontent.com/assets/9346800/16455875/e4f33e3a-3de3-11e6-992b-88765892ba9a.png
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/myjeeed/MakerWear/issues/31#issuecomment-229376387,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABi-9V751Iu1YenEzOOnFkFQP8yCsSBuks5qQoNbgaJpZM4IzmU-
> .

## 

Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich https://twitter.com/jonfroehlich - Twitter
