### ISSUE TITLE
Number

### ISSUE THREAD

**Issue by myjeeed** [myjeeed/MakerWear#32]
The ATtiny85 didn't have enough pins to drive a seven segment!

**Comment by myjeeed** [comment]
We got a working Number module!!

Closing this, other related issues about the Number module will remain open.

**Comment by jonfroehlich** [comment]
Can I see a picture or video please? I hope you guys are taking lots of
pictures/videos as you continue to work on prototypes. Super important.

On Fri, Jun 24, 2016 at 12:50 PM, Majeed notifications@github.com wrote:

> We got a working Number module!!
> 
> Closing this, other related issues about the Number module will remain
> open.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/myjeeed/MakerWear/issues/32#issuecomment-228398824,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABi-9fo3ZKcarU-XeHsdtalzj4ecPuiSks5qPArBgaJpZM4IzmVy
> .

## 

Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich https://twitter.com/jonfroehlich - Twitter

**Comment by jmcpeak2** [comment]
Here is a video

https://drive.google.com/file/d/0BxXWEwzrNM9ZSFYyektfUUtUeFU/view?pref=2&pli=1

**Comment by jonfroehlich** [comment]
This is neat!

On Fri, Jun 24, 2016 at 1:33 PM, jmcpeak2 notifications@github.com wrote:

> Here is a video
> 
> https://drive.google.com/file/d/0BxXWEwzrNM9ZSFYyektfUUtUeFU/view?pref=2&pli=1
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/myjeeed/MakerWear/issues/32#issuecomment-228409683,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABi-9Zl8_rhoWQDZgqMOWeTHv-mnlfXAks5qPBTegaJpZM4IzmVy
> .

## 

Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich https://twitter.com/jonfroehlich - Twitter
