### ISSUE TITLE
DIY Module

### ISSUE THREAD

**Issue by myjeeed** [myjeeed/MakerWear#33]
a new module with a tiny breadboard on top of it. It provides the following pins for users to make new modules for themselves: SIN (Input Signal), SOUT (Output Signal), VDD, and GND.
It requires a voltage follower (made using a rail-to-rail op-amp) on the SIN pin. We are also considering having a small SMD LED on top of this module to visualize what is going through the SOUT pin to the next modules.

**Comment by myjeeed** [comment]
Please test the following items on the DIY module and let us know how they would work:
- PIR Sensor
- Rotational Potentiometers (see if they need any other components to drive)

And after that, please start playing around with the tiny breadboards to add those two holes for the PWR/GND pins.

@jonfroehlich do we need to come up with kid-friendly names for Power and Ground for this module? and can we use abbreviations such as PWR and GND? or their schematic symbols?

**Comment by jonfroehlich** [comment]
Good questions. Do we have room for icons on the DIY breadboard (or whatever kids are going to use to plug in their designs). If so, we could have PWR and GND (or Power and Ground) with icons to help indicate what they do.

As MakerWear is not just about enabling new forms of self-expression and creativity but also learning, I think the DIY is a really neat opportunity to advance learning (in circuits, electrictronics, etc.) so we should leverage this and not shy away from using technical language here (as long as we also have accessible footholds to increase approachability as well).

**Comment by jmcpeak2** [comment]
The PIR sensor works very well. We should add some labels on it to easily identify its three pins (power, ground, and output)

The Rotational Potentiometers also work well, and don't require any additional circuit components. However, we should brainstorm methods to attach them to clothing. They are too large to just be hanging freely off the module's breadboard, and they would be easier to use if they are on a flat surface.

The tiny breadboards are a little too big to fit on the top of the module. However, they have a lot of plastic space on the sides that can be removed. We tried drilling a hole in the plastic to insert the pin we need for "Vout", and it seems to work pretty well. We should also try using the dremel to cut away all the plastic

**Comment by jonfroehlich** [comment]
Ideally, we would have a tiny breadboard on top of the module, right? Can you (or one of the ugrads) look for tiny breadboard alternatives online? I agree that we could dremel or laser cut to shrink-to-fit.

**Comment by myjeeed** [comment]
This is how this module looks like:
![image](https://cloud.githubusercontent.com/assets/9346800/16429502/2693ee24-3d45-11e6-8336-b2e49a82a5ff.png)
![image](https://cloud.githubusercontent.com/assets/9346800/16429510/2bee9cde-3d45-11e6-96cb-6aa42d9be1c8.png)

Now working on the top cover design.

**Comment by jonfroehlich** [comment]
Top cover probably just needs to provide name for module and then labels for those wires. The module itself is a good icon. :)

**Comment by myjeeed** [comment]
what should I use for the labels: input/output/power/ground?

![image](https://cloud.githubusercontent.com/assets/9346800/16820997/f528cd12-4921-11e6-955f-4915b5e5e2fe.png)

**Comment by jonfroehlich** [comment]
I think these labels are fine for now.

The 'in' label should have same font size as 'out' label... maybe move 'in'
text below the pin socket where there is more room?

On Wed, Jul 13, 2016 at 5:48 PM, Majeed notifications@github.com wrote:

> what should I use for the labels: input/output/power/ground?
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/9346800/16820997/f528cd12-4921-11e6-955f-4915b5e5e2fe.png
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/myjeeed/MakerWear/issues/33#issuecomment-232497087,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABi-9dZxSbF6qpyjaQ7zDBRvy6JBPiQdks5qVV0ugaJpZM4IzmZc
> .

## 

Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich https://twitter.com/jonfroehlich - Twitter
