### ISSUE TITLE
Wire Module

### ISSUE THREAD

**Issue by myjeeed** [myjeeed/MakerWear#35]
It consists of two modules that are connected together using two wires (SOUT and GND).

**Comment by myjeeed** [comment]
Brainstorming different icon ideas here:
![image](https://cloud.githubusercontent.com/assets/9346800/16452457/9d29edfe-3dd6-11e6-9e7b-5b6ce2b544d8.png)
![image](https://cloud.githubusercontent.com/assets/9346800/16452570/2773f23e-3dd7-11e6-92c1-8d5202207583.png)

**Comment by myjeeed** [comment]
Brainstorming other names for this module:
1. Connection
2. Extension Cord

**Comment by jonfroehlich** [comment]
I like first one. More literal interpretation and easier to understand meaning. 

Maybe riff on that idea a bit? Thinner wire lines, diff plug types, etc

**Comment by jonfroehlich** [comment]
I like wire tbh. Extension Cord also good but long.

**Comment by jmcpeak2** [comment]
I like the first icon as well. 

Would we need different images for the sending wire module and receiving wire module?

**Comment by myjeeed** [comment]
This is what we currently have - let me know if you have any quick fixes for this (not much time left!)
![image](https://cloud.githubusercontent.com/assets/9346800/16857188/56ae7f3a-49ec-11e6-8a56-98443aec67d6.png)

![image](https://cloud.githubusercontent.com/assets/9346800/16857212/76355e28-49ec-11e6-8018-ffeae35aa376.png)

**Comment by jonfroehlich** [comment]
Seems good enough. I'm confused about directionality but we can fix later if a problem
