### ISSUE TITLE
PulseSensor

### ISSUE THREAD

**Issue by myjeeed** [myjeeed/MakerWear#40]
A physiological heart-rate sensor based on http://pulsesensor.com/

https://learn.adafruit.com/pulse-sensor-displayed-with-neopixels
https://github.com/WorldFamousElectronics/PulseSensor_Amped_Arduino

Sensor sample acquisition and processing happens in the background via the timer 2 interrupt. 2mS sample rate. Thus, PWM on Arduino pins 3 and 11 (ATmega328 pins PD3 and PB3) will not work when using this code, because we are using Timer 2.

**Comment by jonfroehlich** [comment]
So this won't work even on the ATmega328 MakerWear module?

**Comment by myjeeed** [comment]
No, it will just not work on the ATtiny, but will work on the ATmega328!

**Comment by myjeeed** [comment]
@alexjiao125 can you please test this on Arduino?

**Comment by myjeeed** [comment]
We got a working Pulse Sensor!!

Closing this, other related issues regarding the Pulse Sensor will remain open.

**Comment by myjeeed** [comment]
This is how the cover for this module will look like:
![image](https://cloud.githubusercontent.com/assets/9346800/16738393/770375f0-4763-11e6-9068-c4f5da8f8572.png)

other icon options:
![image](https://cloud.githubusercontent.com/assets/9346800/16738420/92029fc0-4763-11e6-8533-df9d4cf97bc3.png)
![image](https://cloud.githubusercontent.com/assets/9346800/16738427/9e994946-4763-11e6-9bfe-30b69782b700.png)

**Comment by jonfroehlich** [comment]
I like it! (and I like the icon used on hexagon best)

On Mon, Jul 11, 2016 at 12:34 PM, Majeed notifications@github.com wrote:

> Reopened #40 https://github.com/myjeeed/MakerWear/issues/40.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/myjeeed/MakerWear/issues/40#event-718973676, or mute
> the thread
> https://github.com/notifications/unsubscribe/ABi-9ZVSJHh2IvtPB8gaK79PlB2KZ3Dtks5qUnB9gaJpZM4I1Xfq
> .

## 

Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich https://twitter.com/jonfroehlich - Twitter
