### ISSUE TITLE
Fade Module

### ISSUE THREAD

**Issue by alexjiao125** [myjeeed/MakerWear#43]
The fade module has mostly been completed.  It starts fading whenever it receives a HIGH signal, although it must receive a LOW signal in order to start fading again.  The duration of the fade is determined by a potentiometer knob on top of the module (anywhere from 10 seconds to an instantaneous fade is possible).   If it receives a LOW then a HIGH signal mid-fade the output voltage will increase a set amount and then start fading again.  

Serial communications seem to mess with the delay function, causing the module to not fade the desired amount of time.  When testing on an LED, the brightness decreases less at the beginning than at the end of the fade; this will be fixed using [gamma correction](https://learn.adafruit.com/led-tricks-gamma-correction/the-issue) on the LED module itself.

**Comment by myjeeed** [comment]
What do you think about this?

![image](https://cloud.githubusercontent.com/assets/9346800/16428315/4eb0d6fc-3d3f-11e6-95bb-cbb51b65e492.png)

(we are not able to use the center of the cover - as the potentiometer has occupied that space)

**Comment by jonfroehlich** [comment]
What do the seconds represent?

If we this module is not controlling a slow decrease in signal amplitude, then maybe Fade is the wrong name...

**Comment by alexjiao125** [comment]
The module does control a decrease in amplitude; the seconds represent how long it takes to decrease the signal all the way down to 0 (this will be controlled via potentiometer on top of the module).

Another thing I noticed about this module is that it does not work well with the old non-gamma-corrected LEDs. The fade is not uniform and smooth in addition to flickering at the end.

**Comment by jonfroehlich** [comment]
I think the icon then needs to indicate a fade somehow. Nothing on icon currently does that. Sole focus is on time.

**Comment by myjeeed** [comment]
How is this one?

![image](https://cloud.githubusercontent.com/assets/9346800/16818487/0dc568fa-4916-11e6-8bbd-d6f3e337748d.png)

**Comment by jonfroehlich** [comment]
Way too abstract.... for a child.

How about make the tick marks somewhat far apart for slow side but make
them increasingly close together for fast side to indicate sense of speed?

Or maybe that's a bad idea. Hmm.

How about putting 10s below the slow (or whatever it is) and (1s) below the
fast to signify the fade time.

On Wed, Jul 13, 2016 at 4:23 PM, Majeed notifications@github.com wrote:

> How is this one?
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/9346800/16818487/0dc568fa-4916-11e6-8bbd-d6f3e337748d.png
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/myjeeed/MakerWear/issues/43#issuecomment-232475235,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABi-9f0W_R9I8dkVxPotRM43tXHwJlKGks5qVUktgaJpZM4I4oni
> .

## 

Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich https://twitter.com/jonfroehlich - Twitter

**Comment by jonfroehlich** [comment]
And/or maybe use a cone or triangle shape that indicates fade speed below
Slow and Fast?

On Wed, Jul 13, 2016 at 4:25 PM, Jon Froehlich jonf@cs.umd.edu wrote:

> Way too abstract.... for a child.
> 
> How about make the tick marks somewhat far apart for slow side but make
> them increasingly close together for fast side to indicate sense of speed?
> 
> Or maybe that's a bad idea. Hmm.
> 
> How about putting 10s below the slow (or whatever it is) and (1s) below
> the fast to signify the fade time.
> 
> On Wed, Jul 13, 2016 at 4:23 PM, Majeed notifications@github.com wrote:
> 
> > How is this one?
> > 
> > [image: image]
> > https://cloud.githubusercontent.com/assets/9346800/16818487/0dc568fa-4916-11e6-8bbd-d6f3e337748d.png
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > https://github.com/myjeeed/MakerWear/issues/43#issuecomment-232475235,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/ABi-9f0W_R9I8dkVxPotRM43tXHwJlKGks5qVUktgaJpZM4I4oni
> > .
> 
> ## 
> 
> Jon Froehlich
> Assistant Professor
> Computer Science
> University of Maryland, College Park
> http://www.cs.umd.edu/~jonf/
> @jonfroehlich https://twitter.com/jonfroehlich - Twitter

## 

Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich https://twitter.com/jonfroehlich - Twitter

**Comment by myjeeed** [comment]
you mean something like this?
![image](https://cloud.githubusercontent.com/assets/9346800/16818878/f3639e80-4917-11e6-8d76-80d96a06a0e5.png)

or other types of speedometer:
a)
![image](https://cloud.githubusercontent.com/assets/9346800/16818892/097f8864-4918-11e6-9901-0e4895ff42ee.png)
b)
![image](https://cloud.githubusercontent.com/assets/9346800/16818914/1fc552ca-4918-11e6-83bc-e5b851ae8efa.png)
c)
![image](https://cloud.githubusercontent.com/assets/9346800/16818963/43cb8de2-4918-11e6-8f58-e723e0e456d5.png)

**Comment by jonfroehlich** [comment]
Yah, not exactly what i meant but better!

On Wed, Jul 13, 2016 at 4:38 PM, Majeed notifications@github.com wrote:

> you mean something like this?
> [image: image]
> https://cloud.githubusercontent.com/assets/9346800/16818878/f3639e80-4917-11e6-8d76-80d96a06a0e5.png
> 
> or other types of speedometer:
> a)
> [image: image]
> https://cloud.githubusercontent.com/assets/9346800/16818892/097f8864-4918-11e6-9901-0e4895ff42ee.png
> b)
> [image: image]
> https://cloud.githubusercontent.com/assets/9346800/16818914/1fc552ca-4918-11e6-83bc-e5b851ae8efa.png
> c)
> [image: image]
> https://cloud.githubusercontent.com/assets/9346800/16818963/43cb8de2-4918-11e6-8f58-e723e0e456d5.png
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/myjeeed/MakerWear/issues/43#issuecomment-232479435,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABi-9eV3fAG3FNeVotgLgCuSEez8x1_Iks5qVUzWgaJpZM4I4oni
> .

## 

Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich https://twitter.com/jonfroehlich - Twitter

**Comment by myjeeed** [comment]
What about this?
![image](https://cloud.githubusercontent.com/assets/9346800/16819188/467e646e-4919-11e6-86c4-8caae7f6ab8d.png)

**Comment by myjeeed** [comment]
or this?
![image](https://cloud.githubusercontent.com/assets/9346800/16819403/41d301e4-491a-11e6-8b11-8da250f53e4c.png)

**Comment by jonfroehlich** [comment]
Is it really 10s and 1s?

If so, then I like this...

(is the top part inconsistent with the other modules that have knobs
though?)

On Wed, Jul 13, 2016 at 4:53 PM, Majeed notifications@github.com wrote:

> or this?
> [image: image]
> https://cloud.githubusercontent.com/assets/9346800/16819403/41d301e4-491a-11e6-8b11-8da250f53e4c.png
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/myjeeed/MakerWear/issues/43#issuecomment-232483201,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABi-9XBc-XDEnEwVFTjfekFljjKyUsocks5qVVA7gaJpZM4I4oni
> .

## 

Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich https://twitter.com/jonfroehlich - Twitter
