### ISSUE TITLE
ATmega328 bootloader delay

### ISSUE THREAD

**Issue by jmcpeak2** [myjeeed/MakerWear#50]
The modules using the ATmega have a small start-up delay (~2 seconds) because of the bootloader on the chip. This can be especially confusing for action modules because when they are first plugged in it appears they are not working.

One solution I found might be to program the ATmega without the bootloader. Here are some helpful links:
- https://www.arduino.cc/en/Hacking/Programmer
- https://arduinoelectronics.wordpress.com/2012/02/10/standalone-atmega-without-arduino-bootloader/

It seems the only downside to this is it makes reprogramming the boards slightly more difficult. Therefore we may want to only remove the bootloader once we have a final version of the code for the module

**Comment by myjeeed** [comment]
Yes, I agree that we should test this new solution out. As Jason mentioned, it has two benefits: we don't need a crystal anymore, the modules will work instantly (similar to our current ATtiny powered modules).

We can probably do another round of PCBs (only for those 6 ATmega powered modules - that would cost around $130) if we would be able to fix this problem on breadboard.

@jmcpeak2 can you please take a short video and post it here that will show the bootloader delay so that Jon could also see the problem? Thank you.

**Comment by jonfroehlich** [comment]
Why wouldn't we need a crystal? I thought the crystal is for the CPU clock,
so abs. necessary for the ATmega regardless of bootloader.

Yes, post more videos guys!

On Fri, Jun 24, 2016 at 1:00 PM, Majeed notifications@github.com wrote:

> Yes, I agree that we should test this new solution out. As Jason
> mentioned, it has two benefits: we don't need a crystal anymore, the
> modules will work instantly (similar to our current ATtiny powered modules).
> 
> We can probably do another round of PCBs (only for those 6 ATmega powered
> modules - that would cost around $130) if we would be able to fix this
> problem on breadboard.
> 
> @jmcpeak2 https://github.com/jmcpeak2 can you please take a short video
> and post it here that will show the bootloader delay so that Jon could also
> see the problem? Thank you.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/myjeeed/MakerWear/issues/50#issuecomment-228401378,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABi-9QJ43yDgHB_jiOuRqb54gANmqs3vks5qPA0rgaJpZM4I9x2y
> .

## 

Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich https://twitter.com/jonfroehlich - Twitter

**Comment by jmcpeak2** [comment]
Not sure if this is the best way to share a video, but try [this link](https://drive.google.com/a/terpmail.umd.edu/file/d/0BxXWEwzrNM9ZS1FLNWtBdFdjcnc/edit?pref=2&pli=1)

You can see that once I plug the module into the socket, it takes a little while for it to actually turn on

**Comment by jonfroehlich** [comment]
Hmm, that's not *so *bad but obviously far from ideal.

I think if we had a small LED on every module that provide instant
indication to the user that things were connected properly, then this delay
wouldn't even be a problem imo.

@myjeeed: did you guys brainstorm providing an LED indicator on the new PCB
runs? (I know we've talked about this quite a few times, just curious if it
came up again--I still think it's a very good idea. I also realize we are
pressed for space on the PCBs).

On Fri, Jun 24, 2016 at 1:19 PM, jmcpeak2 notifications@github.com wrote:

> Not sure if this is the best way to share a video, but try this link
> https://drive.google.com/a/terpmail.umd.edu/file/d/0BxXWEwzrNM9ZS1FLNWtBdFdjcnc/edit?pref=2&pli=1
> 
> You can see that once I plug the module into the socket, it takes a little
> while for it to actually turn on
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/myjeeed/MakerWear/issues/50#issuecomment-228406341,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABi-9Z3vbPPcuTwDnIfca-uj1Erwszsyks5qPBGugaJpZM4I9x2y
> .

## 

Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich https://twitter.com/jonfroehlich - Twitter

**Comment by myjeeed** [comment]
@jonfroehlich it will be similar to our current ATtiny architecture that uses the internal oscillator on the processors.

Regarding the LED indicator, I don't remember that this has came up again! But I believe that this is a very good idea, especially for Sensors and Modifiers.
Though in terms of implementation, yes we can have a small LED somewhere on the top PCB or the bottom PCB to indicate that it is powered up and working. However, I think that the main reason we would like to have such an LED on each module is for debugging and allowing children to see if they have connected it in the right way. I believe that this makes the circuit and code a little bit more complicated, though I have not thought about it deeply enough.

**Comment by jonfroehlich** [comment]
I agree.

On-board surface mount LEDs could be used for:
- providing immediate feedback that a module is placed correctly and
  connected
- providing different types of debugging info

Jon

On Fri, Jun 24, 2016 at 2:08 PM, Majeed notifications@github.com wrote:

> @jonfroehlich https://github.com/jonfroehlich it will be similar to our
> current ATtiny architecture that uses the internal oscillator on the
> processors.
> 
> Regarding the LED indicator, I don't remember that this has came up again!
> But I believe that this is a very good idea, especially for Sensors and
> Modifiers.
> Though in terms of implementation, yes we can have a small LED somewhere
> on the top PCB or the bottom PCB to indicate that it is powered up and
> working. However, I think that the main reason we would like to have such
> an LED on each module is for debugging and allowing children to see if they
> have connected it in the right way. I believe that this makes the circuit
> and code a little bit more complecated, though I have not thought about it
> deeply enough.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/myjeeed/MakerWear/issues/50#issuecomment-228418546,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABi-9dyMpkKywWs3bmaTAYRoJ7JI2vhIks5qPB0fgaJpZM4I9x2y
> .

## 

Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich https://twitter.com/jonfroehlich - Twitter

**Comment by jmcpeak2** [comment]
I was able to get the SMD ATMega to work without the bootloader, which eliminated this delay. It also works without an external crystal. Here are the steps I followed:
1. Follow the instructions listed on the "Minimal Circuit" section of this Arduino tutorial in order to add the "ATmega328 on a breadboard (8 MHz internal clock)" board to the Arduino IDE. (https://www.arduino.cc/en/Tutorial/ArduinoToBreadboard)
2. In the "boards.txt" file you should have just downloaded (found in Arduino\hardware\breadboard\avr) make the following changes:
   - `atmega328bb.upload.maximum_size=30720` should become `atmega328bb.upload.maximum_size=32768`
   - add the line `atmega328bb.upload.using=arduino:arduinoisp`
3. Restart Arduino IDE
4. Wire the Arduino like this:
   
   ![arduinoisp2](https://cloud.githubusercontent.com/assets/19734849/16383781/7c4c0424-3c54-11e6-8185-a0993c081f6f.png)
5. Assuming you have the ArduinoISP programmed on the Arduino, program the chip by selecting "ATmega328 on a breadboard (8 MHz internal clock)" as the board, and using the Sketch->Upload Using Programmer command. (not the normal upload button)
