### ISSUE TITLE
Empty Space In Module: needs to be filled with something

### ISSUE THREAD

**Issue by myjeeed** [myjeeed/MakerWear#52]
Power Modules, DIY Modules and all of the new ATmega powered modules are very fragile and easily broken if too much force and pressure is applied to the top PCB (mostly the side of the module with no support). Currently, the ATtiny powered modules use the ATtiny as a good support and will not break easily if pressure is applied to its top PCB.

![image](https://cloud.githubusercontent.com/assets/9346800/16355728/732e1692-3a8e-11e6-989d-a5e492b70d6c.png)

**Comment by jonfroehlich** [comment]
Can we reduce height of the three pin connector, so the upper PCB rests on the magnet?

If not, then we should choose filler material that is very lightweight and easy to apply so doesn't dramatically increase manufacturing time for us.

**Comment by alexjiao125** [comment]
I think reducing the height of the pin connector would be less ideal because we want all the modules to be at a similar height when they're on the socket.  Maybe a piece of foam or something on top of the magnet would work?

**Comment by jonfroehlich** [comment]
Would foam provide sufficient support?

On Sun, Jun 26, 2016 at 10:38 AM, Alexander Jiao notifications@github.com
wrote:

> I think reducing the height of the pin connector would be less ideal
> because we want all the modules to be at a similar height when they're on
> the socket. Maybe a piece of foam or something on top of the magnet would
> work?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/myjeeed/MakerWear/issues/52#issuecomment-228604386,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABi-9ZxiVdxq1rUPMMUgSD7oJhoH0h89ks5qPo7igaJpZM4I-TMt
> .

## 

Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich https://twitter.com/jonfroehlich - Twitter

**Comment by alexjiao125** [comment]
I tested the foam today and it was indeed too soft.  I also tried using cork which was much more stiff.  I will keep on experimenting with different shapes of cork cutouts. Fyi I measured the distances between the top and bottom PCBs on an ATtiny module to be .25 inches exact.  
![image](https://cloud.githubusercontent.com/assets/17015893/16393443/d6fbae2c-3c7e-11e6-8764-08bdf6de0557.png)

**Comment by jonfroehlich** [comment]
Anyway to simply reduce the height of all modules? A slimmer design is obviously preferred.

**Comment by alexjiao125** [comment]
The ATtiny modules can't really be made any slimmer.  Right now the ATtiny is pushed against the top of the magnet.

**Comment by jonfroehlich** [comment]
Got it. Ok, cork seems like a nice choice as its lightweight. Could also try foamcore but that may be too compressible. We can laser cut those materials to accelerate manufacturing.
