### ISSUE TITLE
Confusing Names: Pulse Maker, Pulse Meter, Pulse Sensor

### ISSUE THREAD

**Issue by jmcpeak2** [myjeeed/MakerWear#54]
We currently have three modules with very similar names:
- Pulse Maker - Modifier module that creates voltage pulses
- Pulse Meter - Modifier module that measures frequency of input pulses
- Pulse Sensor - Measures Heartbeat 

This is somewhat confusing, so we should come up with better names.

**Comment by jonfroehlich** [comment]
I agree.

The last one is an easy fix:
Pulse Sensor -> Heartbeat Monitor or Heartbeat Sensor

On Mon, Jun 27, 2016 at 2:24 PM, jmcpeak2 notifications@github.com wrote:

> We currently have three modules with very similar names:
> - Pulse Maker - Modifier module that creates voltage pulses
> - Pulse Meter - Modifier module that measures frequency of input pulses
> - Pulse Sensor - Measures Heartbeat
> 
> This is somewhat confusing, so we should come up with better names.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/myjeeed/MakerWear/issues/54, or mute the thread
> https://github.com/notifications/unsubscribe/ABi-9dAcGvCYO5Fvi5ABRfcE8wGPcsBzks5qQBVegaJpZM4I_XnK
> .

## 

Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich https://twitter.com/jonfroehlich - Twitter

**Comment by myjeeed** [comment]
Pulse Maker -> waveform generator? - I like the name PulseMaker much more.
Pulse Meter -> frequency detector? beat detector?

**Comment by myjeeed** [comment]
Current names:
- SineGenerator
- SquareGenerator
- HeartbeatDetector

**Comment by jonfroehlich** [comment]
I think we need to have the word 'wave' in there, so how about:
- Sine Wave Generator
- Square Wave Generator
- Heartbeat Detector

**Comment by myjeeed** [comment]
Icons for these modules:

![image](https://cloud.githubusercontent.com/assets/9346800/16815786/3ba6576e-4909-11e6-96df-63fdbaacec0c.png)

![image](https://cloud.githubusercontent.com/assets/9346800/16815836/828a1d5a-4909-11e6-9494-c00ff04eeed6.png)

**Comment by jonfroehlich** [comment]
I really like this. What do the intermediate tick marks indicate? If
nothing, maybe take them out?

On Wed, Jul 13, 2016 at 2:53 PM, Majeed notifications@github.com wrote:

> Icons for these modules:
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/9346800/16815786/3ba6576e-4909-11e6-96df-63fdbaacec0c.png
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/9346800/16815836/828a1d5a-4909-11e6-9494-c00ff04eeed6.png
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/myjeeed/MakerWear/issues/54#issuecomment-232451710,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABi-9SshcFcDmLM7zWT-FnVcZrorxaJtks5qVTQYgaJpZM4I_XnK
> .

## 

Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich https://twitter.com/jonfroehlich - Twitter
