### ISSUE TITLE
Wave Generation Brainstorming

### ISSUE THREAD

**Issue by jmcpeak2** [myjeeed/MakerWear#55]
We had an idea for a module with a switch that could select between different waveform types. (sine, square, sawtooth, etc). Connecting this module to action modules would help kids visualize how these signals are different from each other. Here are some ideas we had for different waveform modules:
- We could have the waveform modules as power modules (red cover). They would always output signals from low to high and would take no input (6 outputs). We could either have one waveform module with a potentiometer on top to select between different types of waves, or individual modules for each type 
- We could also have one single modifier with a potentiometer on top to select between different types of waves. In this case, the output of the module would vary from low to whatever the module receives as input. An issue with this however is that there would be no way to configure frequency of the wave generated
- Finally, we could have separate modifier modules for each type of waveform. Each of these would have a potentiometer on top that would change the frequency of the signal that they output.

I like the final idea the best.

**Another note**: The PulseMaker module we currently have varies both the amplitude and frequency of its output depending on the input. For example, sending it a value close to 0 would create a slow pulse with small amplitude, while a high value would create a fast pulse with high amplitude. This should be changed because it is confusing to have two different parameters changing based on the input.

**Comment by alexjiao125** [comment]
I agree with the last paragraph.  To keep the PulseMaker consistent with other modifiers, I think we should change it to have a potentiometer on top to determine the frequency of the pulses and have the amplitude determined by input voltage.  This will be similar to the current Fade and Threshold modules.

**Comment by myjeeed** [comment]
I totally agree that the PulseMaker right now does not have a consistent behavior. For example having a VolumeKnob before it vs. having one after it is totally a different thing. The one that is before it will adjust both the Frequency and the max voltage of the output waveform, however, the one that is after it will only adjust the max voltage of the output signal.

These are the different kinds of waveforms that we are interested to make:
1. SquareGenerator
2. SineGenerator
3. RampGenerator

Based on that, we have two different options:
1. Make one single module with a knob that would select between frequencies and different functions
2. Make three separate modules that each would only output one kind of signal but the output frequency is adjustable using the knob.

**Comment by alexjiao125** [comment]
I tested out a sin wave generator, and have attached a video below.  As you can see the input determines amplitude and the potentiometer knob determines frequency.  There is noticeable flickering, especially while a potentiometer is being turned.  I noticed that this flickering is only apparent at lower amplitudes. 

video: https://drive.google.com/open?id=0B4DVQ8s4MQhxRklscC1rNG5XMUE

**Comment by myjeeed** [comment]
This is great, can you also test with other frequencies? For example from 0.1Hz to 10Hz.

Yes, it seems that the LED will flicker when the PWM value changes from 0 to 1.

Thanks.

**Comment by alexjiao125** [comment]
I also tested out a saw wave, and it is not a lot different from the sine wave.  Jason suggested doing a sort of /|/|/| would contrast better with the sine wave than a /\/\/\/\

**Comment by jonfroehlich** [comment]
Yep, Jason's suggestion is consistent w the saw waves I'm familiar with. Did you look up the Oscilloscope to view these?

**Comment by jonfroehlich** [comment]
Majeed, can you please download all of these videos that the team is posting and put in Dropbox for posterity. I assume that Jason/Alex will likely remove the videos at some point from Google Drive which would prevent us from accessing them in future.

**Comment by alexjiao125** [comment]
Here is a video of a "hybrid wave" module.  One half of the potentiometer controls a sine wave and the other half controls a triangle (/|/|/|/|) wave.  @jonfroehlich We were discussing whether we should have 3 separate modules for the square, sine and triangle waves or have all 3 of them on a module such as this.  Personally, I think we could forget about the triangle and just have the square and sine waves on a single module.

https://drive.google.com/open?id=0B4DVQ8s4MQhxa2RwUk5rM3RTNDg

**Comment by jonfroehlich** [comment]
In terms of building appropriate mental models, I wonder if best to have a DIP or slide switch to toggle between sine, square, and triangle (or just done and square if we end up w that) then potentiometer is just for frequency control. 

As now, mapping multiple things onto pot could be confusing and is inconsistent w other modules.

**Comment by myjeeed** [comment]
So lets just have them in separate modules for now:
- SquareGenerator
- SineGenerator

**Comment by myjeeed** [comment]
@jonfroehlich all of the videos are now saved in our shared DropBox folder.

**Comment by jonfroehlich** [comment]
Sounds good.

**Comment by jonfroehlich** [comment]
Great!
