### ISSUE TITLE
ColorDetector: cover

### ISSUE THREAD

**Issue by myjeeed** [myjeeed/MakerWear#63]
What do you think about this?
![image](https://cloud.githubusercontent.com/assets/9346800/16739512/890d3812-4768-11e6-93a8-58d219e54aa5.png)

I'm trying to make it look like an eyedropper!

![image](https://cloud.githubusercontent.com/assets/9346800/16739606/0607844e-4769-11e6-89fa-eb45e455c20d.png)
or
![image](https://cloud.githubusercontent.com/assets/9346800/16739690/6349d7a6-4769-11e6-98c6-f01a702ec794.png)

**Comment by jonfroehlich** [comment]
I like it

**Comment by jonfroehlich** [comment]
Looks too much like a sword though and not sure if young children will be familiar w eye dropper concept... But I say go w it a d just improve eye dropper icon to not look like sword

**Comment by myjeeed** [comment]
Brainstorming different eyedropper icons here:
a)
![image](https://cloud.githubusercontent.com/assets/9346800/16770274/38d94676-481a-11e6-8ad1-5519fd3619d1.png)
b)
![image](https://cloud.githubusercontent.com/assets/9346800/16770315/7440beb0-481a-11e6-9be4-9490a613e1d6.png)
c)
![image](https://cloud.githubusercontent.com/assets/9346800/16770322/7f05f234-481a-11e6-823a-64d5ba99dde4.png)
d)
![image](https://cloud.githubusercontent.com/assets/9346800/16770342/91d740c0-481a-11e6-84e3-6d93d16869b0.png)
e)
![image](https://cloud.githubusercontent.com/assets/9346800/16770353/9846edc0-481a-11e6-9002-beb7b2a9883c.png)
f)
![image](https://cloud.githubusercontent.com/assets/9346800/16770374/b3a326a6-481a-11e6-9a47-1723f7ace12d.png)
g)
![image](https://cloud.githubusercontent.com/assets/9346800/16770383/bc709fc0-481a-11e6-8278-2ee554a52dca.png)
h)
![image](https://cloud.githubusercontent.com/assets/9346800/16770395/cdcadd1c-481a-11e6-9f94-c3936d06e774.png)
i)
![image](https://cloud.githubusercontent.com/assets/9346800/16770417/e25c5224-481a-11e6-9233-b93c44ea3906.png)

**Comment by jmcpeak2** [comment]
I like d and b the best. f is good too

**Comment by jonfroehlich** [comment]
b or c

On Tue, Jul 12, 2016 at 10:34 AM, jmcpeak2 notifications@github.com wrote:

> I like d and b the best. f is good too
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/myjeeed/MakerWear/issues/63#issuecomment-232066639,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABi-9VdDse1N0hrfB6Yr21P5BG2pMkMXks5qU6XygaJpZM4JJlTI
> .

## 

Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich https://twitter.com/jonfroehlich - Twitter

**Comment by myjeeed** [comment]
are these any better?
![image](https://cloud.githubusercontent.com/assets/9346800/16821349/be4526e0-4923-11e6-8598-cfa3426e40f9.png)

![image](https://cloud.githubusercontent.com/assets/9346800/16821665/80a56d34-4925-11e6-9926-fa8c6ac2ade2.png)

**Comment by myjeeed** [comment]
or this?
![image](https://cloud.githubusercontent.com/assets/9346800/16823428/1d616ad6-4932-11e6-85c1-86bfea317f38.png)

**Comment by myjeeed** [comment]
or this?
![image](https://cloud.githubusercontent.com/assets/9346800/16823485/abdf45c6-4932-11e6-8cb5-c43109ff91c6.png)

**Comment by myjeeed** [comment]
Though coloring these will be hard, and it won't look that great! :(

**Comment by jonfroehlich** [comment]
Yah, not sure. I do like the most recent one (https://github.com/myjeeed/MakerWear/issues/63#issuecomment-232519184) but I also like this thing: 
![image](https://cloud.githubusercontent.com/assets/1621749/16824110/186c6242-4937-11e6-83b4-45161362ba98.png) (of course, I'm not sure that metaphor is going to make sense to young children).

I think the dropper icon you used is better now (doesn't look like a sword as much).
