### ISSUE TITLE
Distance Sensor and Number: Stops working at high distance

### ISSUE THREAD

**Issue by jmcpeak2** [myjeeed/MakerWear#67]
We saw some strange behavior when we had the distance sensor attached directly to the number module. The sensor would work properly as long as we kept our hand withing the 0-9 range, but once the distance increased too far away the sensor would stop responding. 

This problem also did not occur on all of the sockets, but on  just one of the vests we tested on. We need to investigate this further.

@myjeeed can post a video showing this happening.

**Comment by myjeeed** [comment]
This never happened again, and we think it was a problem about the sockets... :)

Closing this issue.
