### ISSUE TITLE
Sockets Different Sizes

### ISSUE THREAD

**Issue by alexjiao125** [myjeeed/MakerWear#69]
Me and Jason noticed today that the sockets on the vests seem smaller than the ones on the attachable sockets. This means that the modules may not need filing as we previously thought.

**Comment by myjeeed** [comment]
We were able to fix this using the Exacto knife, am I right?
Though I still think that some of the modules need to be filled a little bit more to make sure that they fit in to sockets easily.

**Comment by myjeeed** [comment]
This was fixed, closing the issue.
