### ISSUE TITLE
Distance Sensor: increase range

### ISSUE THREAD

**Issue by myjeeed** [myjeeed/MakerWear#9]
Currently the range is very short and limits its applications when building things.

**Comment by alexjiao125** [comment]
Additionally, if an object is too close to the sensor (within 1 cm), it will register it as being further away again.

**Comment by jonfroehlich** [comment]
A few ideas here:
- Can we make the range settable either via an onboard potentiometer (like littleBits) or via some modular connections?
- If the above doesn't work, can we have a few different modules--one for short distance, one for medium, one for long (this is less preferable than above)

Note: I feel the same way about the light sensor as the distance sensor. Would be nice if the light sensitivity was easily adjustable. Thoughts?

**Comment by myjeeed** [comment]
I think that adding a small potentiometer to adjust the sensitivity of a number of modules is definitely a good idea. Sensors such as the **Motion Detector**, **Light Sensor**, **Distance Sensor**, **Sunlight Detector** (UV Light) as well as future **Temperature Sensor** and **Sound Sensor** would benefit from this.

**Comment by myjeeed** [comment]
Regarding the Infrared Distance Sensor, this seems to be a promising new design for a next iteration: 
![image](https://cloud.githubusercontent.com/assets/9346800/15799818/a73a08b8-2a37-11e6-8447-2eb00674c502.png)

Video and instructions: http://www.instructables.com/id/Simple-IR-proximity-sensor-with-Arduino/

**Comment by jmcpeak2** [comment]
This would help to decrease the current draw of the sensor when it is powered off. Currently, it is drawing around 93mA even when it is not connected to any other modules

**Comment by myjeeed** [comment]
I am designing a new PCB for the DistanceSensor to fix the power issue as well as the small range of distance problem.

**Comment by myjeeed** [comment]
A few things that @alexjiao125 or @jmcpeak2 need to experiment for me while I am designing the new PCBs for this module:
- does having a small gap between the two IR LEDs affect the range of distances we're able to measure?
- how does the resistor values affect this?
- I have purchased a few different models for the transmitter IRs and receiver IRs, can you see what combinations results in the best and biggest range of measured distances?

**Comment by alexjiao125** [comment]
I tried the distance sensor with 2 IR LEDs. This is the regression I got; it seems pretty accurate.

![exponentialregression](https://cloud.githubusercontent.com/assets/17015893/16592014/a74867d6-42ac-11e6-952e-3ac7da66e2d4.jpg)

**Comment by jonfroehlich** [comment]
What are the implications here--specifically, of the non-linearity? Did we
expect a linear regression between voltage and distance?

On Tue, Jul 5, 2016 at 12:33 PM, Alexander Jiao notifications@github.com
wrote:

> I tried the distance sensor with 2 IR LEDs. This is the regression I got;
> it seems pretty accurate.
> 
> [image: exponentialregression]
> https://cloud.githubusercontent.com/assets/17015893/16592014/a74867d6-42ac-11e6-952e-3ac7da66e2d4.jpg
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/myjeeed/MakerWear/issues/9#issuecomment-230531111,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABi-9b7hQ8-F1Ucu0wYLsS8XdGJgXqDVks5qSodWgaJpZM4ItvnJ
> .

## 

Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich https://twitter.com/jonfroehlich - Twitter
